project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Quantitative Analysis and Data Visualisation Using R"
  author: 
    - "Sophie Lee"
    - "Dean Marchiori"
  downloads: [pdf]  
  search: true
  navbar:
    right: 
      - icon: github
        href: https://github.com/deanmarchiori/intro-quant-analysis
        aria-label: Github
  chapters:
    - index.qmd
    - session1_notes.qmd
    - session2_notes.qmd
    - session3_notes.qmd
    - session4_notes.qmd
    - session5_notes.qmd
  appendices: 
    - data_description.qmd
    - exercise_solutions.qmd
    - setup.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt



